resource: get resource primary from boot partition
resource partition is always present in parameter file even we use ota
firmware which packes resource file in boot.img, don't try to verify
resource partition depends on parameter info.

fix U-Boot boot issue, log is like below:
......
read logo on state from dts [1]
ERROR: [get_entry]: Not a resource image!
failed to display uboot logo
ERROR: [get_entry]: Not a resource image!
failed to display kernel logo
......

Change-Id: I24a934341420b14c93a0d9b35d5e7c9449ebd339
Signed-off-by: Joseph Chen <chenjh@rock-chips.com>