zircon.c: Delete unused variables [1/1]
PD#SWPL-85500

Problem:
../board/amlogic/g12b_w400_v1/zircon.c:123:41: error: ‘hdcp_driver’
defined but not used [-Werror=unused-const-variable=]
../board/amlogic/g12b_w400_v1/zircon.c:58:31: error: ‘cpu_config’
defined but not used [-Werror=unused-const-variable=]

Solution:
Delete unused variables.

Verify:
./mk --check-compile
 024 g12b_w400_v1 ------------------- pass
 025 g12b_w400_v1_zircon ------------ pass
 026 g12b_w411_v1 ------------------- pass

Change-Id: Ib988a086869f8ea503c72f17462ba8abf344f89b
Signed-off-by: dingxin.jin <dingxin.jin@amlogic.com>